/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CBDCAccountChild {
  id?: number;
  accountOwningPIPId?: number;
  status?: CBDCAccountChild.StatusEnum;
}
export namespace CBDCAccountChild {
  export type StatusEnum = 'OPEN' | 'CLOSED';
  export const StatusEnum = {
    OPEN: 'OPEN' as StatusEnum,
    CLOSED: 'CLOSED' as StatusEnum,
  };
}
