/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Currency } from './currency';
import { RegisteredParty } from './registeredParty';

export interface PIPView {
  id?: number;
  status?: PIPView.StatusEnum;
  currency?: Currency;
  pipName?: string;
  parties?: Array<RegisteredParty>;
  accounts?: Array<Account>;
}
export namespace PIPView {
  export type StatusEnum = 'ACTIVE' | 'TERMINATED';
  export const StatusEnum = {
    ACTIVE: 'ACTIVE' as StatusEnum,
    TERMINATED: 'TERMINATED' as StatusEnum,
  };
}
