/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RegisterPartyRequestBody {
  partyType?: RegisterPartyRequestBody.PartyTypeEnum;
  partyFullLegalName?: string;
  partyPostalAddress?: string;
}
export namespace RegisterPartyRequestBody {
  export type PartyTypeEnum = 'INDIVIDUAL' | 'PUBLIC_LIMITED_COMPANY' | 'PRIVATE_LIMITED_COMPANY';
  export const PartyTypeEnum = {
    INDIVIDUAL: 'INDIVIDUAL' as PartyTypeEnum,
    PUBLICLIMITEDCOMPANY: 'PUBLIC_LIMITED_COMPANY' as PartyTypeEnum,
    PRIVATELIMITEDCOMPANY: 'PRIVATE_LIMITED_COMPANY' as PartyTypeEnum,
  };
}
