/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { BadRequestResponse } from '../model/badRequestResponse';
import { CreatePaymentConsentResponseBody } from '../model/createPaymentConsentResponseBody';
import { ErrorResponseBody } from '../model/errorResponseBody';
import { GetDomesticPaymentDetailsResponseBody } from '../model/getDomesticPaymentDetailsResponseBody';
import { GetPaymentConsentResponseBody } from '../model/getPaymentConsentResponseBody';
import { MakeDomesticPaymentResponseBody } from '../model/makeDomesticPaymentResponseBody';
import { NotFoundResponse } from '../model/notFoundResponse';
import { OpenBankingPaymentConsentCreationRequestBody } from '../model/openBankingPaymentConsentCreationRequestBody';
import { PaymentInitiationDetails } from '../model/paymentInitiationDetails';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class OBPISPService {
  protected basePath = 'https://cbdchackathon-dev.barclays.nayaone.com/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Grant consent to a banking entity to initiate a payment.
   * Simulates the action of a party granting consent for a payment to be made from their account.
   * @param body
   * @param xEnvId Identifier for the environment.
   * @param xCurrencyId Identifier for the currency.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public obCreatePaymentConsent(
    body: OpenBankingPaymentConsentCreationRequestBody,
    xEnvId: number,
    xCurrencyId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<CreatePaymentConsentResponseBody>;
  public obCreatePaymentConsent(
    body: OpenBankingPaymentConsentCreationRequestBody,
    xEnvId: number,
    xCurrencyId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<CreatePaymentConsentResponseBody>>;
  public obCreatePaymentConsent(
    body: OpenBankingPaymentConsentCreationRequestBody,
    xEnvId: number,
    xCurrencyId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<CreatePaymentConsentResponseBody>>;
  public obCreatePaymentConsent(
    body: OpenBankingPaymentConsentCreationRequestBody,
    xEnvId: number,
    xCurrencyId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling obCreatePaymentConsent.');
    }

    if (xEnvId === null || xEnvId === undefined) {
      throw new Error('Required parameter xEnvId was null or undefined when calling obCreatePaymentConsent.');
    }

    if (xCurrencyId === null || xCurrencyId === undefined) {
      throw new Error('Required parameter xCurrencyId was null or undefined when calling obCreatePaymentConsent.');
    }

    let headers = this.defaultHeaders;
    if (xEnvId !== undefined && xEnvId !== null) {
      headers = headers.set('x-env-id', String(xEnvId));
    }
    if (xCurrencyId !== undefined && xCurrencyId !== null) {
      headers = headers.set('x-currency-id', String(xCurrencyId));
    }

    // authentication (x-api-key) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['x-api-key']) {
      headers = headers.set('x-api-key', this.configuration.apiKeys['x-api-key']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<CreatePaymentConsentResponseBody>(
      'post',
      `${this.basePath}/open-banking/pisp/domestic-payment-consents`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get payment details .
   * Retrieve the latest status of a payment.
   * @param xEnvId Identifier for the environment.
   * @param xCurrencyId Identifier for the currency.
   * @param xRequestingBankingEntityId Identifier for the banking entity (commercial bank/pip) which you are simulating is making this API call. This is the banking entity which needs to have been granted consent from the party.
   * @param xConsentId Identifier for the consent resource which grants access to perform this request.
   * @param domesticPaymentId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public obGetPayment(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    domesticPaymentId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GetDomesticPaymentDetailsResponseBody>;
  public obGetPayment(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    domesticPaymentId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GetDomesticPaymentDetailsResponseBody>>;
  public obGetPayment(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    domesticPaymentId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GetDomesticPaymentDetailsResponseBody>>;
  public obGetPayment(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    domesticPaymentId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (xEnvId === null || xEnvId === undefined) {
      throw new Error('Required parameter xEnvId was null or undefined when calling obGetPayment.');
    }

    if (xCurrencyId === null || xCurrencyId === undefined) {
      throw new Error('Required parameter xCurrencyId was null or undefined when calling obGetPayment.');
    }

    if (xRequestingBankingEntityId === null || xRequestingBankingEntityId === undefined) {
      throw new Error('Required parameter xRequestingBankingEntityId was null or undefined when calling obGetPayment.');
    }

    if (xConsentId === null || xConsentId === undefined) {
      throw new Error('Required parameter xConsentId was null or undefined when calling obGetPayment.');
    }

    if (domesticPaymentId === null || domesticPaymentId === undefined) {
      throw new Error('Required parameter domesticPaymentId was null or undefined when calling obGetPayment.');
    }

    let headers = this.defaultHeaders;
    if (xEnvId !== undefined && xEnvId !== null) {
      headers = headers.set('x-env-id', String(xEnvId));
    }
    if (xCurrencyId !== undefined && xCurrencyId !== null) {
      headers = headers.set('x-currency-id', String(xCurrencyId));
    }
    if (xRequestingBankingEntityId !== undefined && xRequestingBankingEntityId !== null) {
      headers = headers.set('x-requesting-banking-entity-id', String(xRequestingBankingEntityId));
    }
    if (xConsentId !== undefined && xConsentId !== null) {
      headers = headers.set('x-consent-id', String(xConsentId));
    }

    // authentication (x-api-key) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['x-api-key']) {
      headers = headers.set('x-api-key', this.configuration.apiKeys['x-api-key']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GetDomesticPaymentDetailsResponseBody>(
      'get',
      `${this.basePath}/open-banking/pisp/domestic-payments/${encodeURIComponent(String(domesticPaymentId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get the state of a consent resource.
   * Get the state of a consent resource which has been previously created.
   * @param xEnvId Identifier for the environment.
   * @param xCurrencyId Identifier for the currency.
   * @param xRequestingBankingEntityId Identifier for the banking entity (commercial bank/pip) which you are simulating is making this API call. This is the banking entity which needs to have been granted consent from the party.
   * @param consentId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public obGetPaymentConsent(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    consentId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GetPaymentConsentResponseBody>;
  public obGetPaymentConsent(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    consentId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GetPaymentConsentResponseBody>>;
  public obGetPaymentConsent(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    consentId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GetPaymentConsentResponseBody>>;
  public obGetPaymentConsent(
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    consentId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (xEnvId === null || xEnvId === undefined) {
      throw new Error('Required parameter xEnvId was null or undefined when calling obGetPaymentConsent.');
    }

    if (xCurrencyId === null || xCurrencyId === undefined) {
      throw new Error('Required parameter xCurrencyId was null or undefined when calling obGetPaymentConsent.');
    }

    if (xRequestingBankingEntityId === null || xRequestingBankingEntityId === undefined) {
      throw new Error('Required parameter xRequestingBankingEntityId was null or undefined when calling obGetPaymentConsent.');
    }

    if (consentId === null || consentId === undefined) {
      throw new Error('Required parameter consentId was null or undefined when calling obGetPaymentConsent.');
    }

    let headers = this.defaultHeaders;
    if (xEnvId !== undefined && xEnvId !== null) {
      headers = headers.set('x-env-id', String(xEnvId));
    }
    if (xCurrencyId !== undefined && xCurrencyId !== null) {
      headers = headers.set('x-currency-id', String(xCurrencyId));
    }
    if (xRequestingBankingEntityId !== undefined && xRequestingBankingEntityId !== null) {
      headers = headers.set('x-requesting-banking-entity-id', String(xRequestingBankingEntityId));
    }

    // authentication (x-api-key) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['x-api-key']) {
      headers = headers.set('x-api-key', this.configuration.apiKeys['x-api-key']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GetPaymentConsentResponseBody>(
      'get',
      `${this.basePath}/open-banking/pisp/domestic-payment-consents/${encodeURIComponent(String(consentId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Make a payment.
   * Make a payment for which consent has previously been given.
   * @param body
   * @param xEnvId Identifier for the environment.
   * @param xCurrencyId Identifier for the currency.
   * @param xRequestingBankingEntityId Identifier for the banking entity (commercial bank/pip) which you are simulating is making this API call. This is the banking entity which needs to have been granted consent from the party.
   * @param xConsentId Identifier for the consent resource which grants access to perform this request.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public obMakePayment(
    body: PaymentInitiationDetails,
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<MakeDomesticPaymentResponseBody>;
  public obMakePayment(
    body: PaymentInitiationDetails,
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<MakeDomesticPaymentResponseBody>>;
  public obMakePayment(
    body: PaymentInitiationDetails,
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<MakeDomesticPaymentResponseBody>>;
  public obMakePayment(
    body: PaymentInitiationDetails,
    xEnvId: number,
    xCurrencyId: number,
    xRequestingBankingEntityId: number,
    xConsentId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling obMakePayment.');
    }

    if (xEnvId === null || xEnvId === undefined) {
      throw new Error('Required parameter xEnvId was null or undefined when calling obMakePayment.');
    }

    if (xCurrencyId === null || xCurrencyId === undefined) {
      throw new Error('Required parameter xCurrencyId was null or undefined when calling obMakePayment.');
    }

    if (xRequestingBankingEntityId === null || xRequestingBankingEntityId === undefined) {
      throw new Error('Required parameter xRequestingBankingEntityId was null or undefined when calling obMakePayment.');
    }

    if (xConsentId === null || xConsentId === undefined) {
      throw new Error('Required parameter xConsentId was null or undefined when calling obMakePayment.');
    }

    let headers = this.defaultHeaders;
    if (xEnvId !== undefined && xEnvId !== null) {
      headers = headers.set('x-env-id', String(xEnvId));
    }
    if (xCurrencyId !== undefined && xCurrencyId !== null) {
      headers = headers.set('x-currency-id', String(xCurrencyId));
    }
    if (xRequestingBankingEntityId !== undefined && xRequestingBankingEntityId !== null) {
      headers = headers.set('x-requesting-banking-entity-id', String(xRequestingBankingEntityId));
    }
    if (xConsentId !== undefined && xConsentId !== null) {
      headers = headers.set('x-consent-id', String(xConsentId));
    }

    // authentication (x-api-key) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['x-api-key']) {
      headers = headers.set('x-api-key', this.configuration.apiKeys['x-api-key']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<MakeDomesticPaymentResponseBody>('post', `${this.basePath}/open-banking/pisp/domestic-payments`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }
}
