/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingEntityWhereConsentGrantingPartyIsRegisteredRef } from './bankingEntityWhereConsentGrantingPartyIsRegisteredRef';
import { ConsentGrantingPartyId } from './consentGrantingPartyId';
import { ConsentRequestingBankingEntityRef } from './consentRequestingBankingEntityRef';

export interface AccountAccessConsentView {
  accountAccessConsentId?: number;
  status?: AccountAccessConsentView.StatusEnum;
  consentConsentGrantingPartyId?: ConsentGrantingPartyId;
  consentRequestingBankingEntityRef?: ConsentRequestingBankingEntityRef;
  bankingEntityWhereConsentGrantingPartyIsRegisteredRef?: BankingEntityWhereConsentGrantingPartyIsRegisteredRef;
}
export namespace AccountAccessConsentView {
  export type StatusEnum = 'AWAITING_AUTHORISATION' | 'REJECTED' | 'AUTHORISED' | 'REVOKED';
  export const StatusEnum = {
    AWAITINGAUTHORISATION: 'AWAITING_AUTHORISATION' as StatusEnum,
    REJECTED: 'REJECTED' as StatusEnum,
    AUTHORISED: 'AUTHORISED' as StatusEnum,
    REVOKED: 'REVOKED' as StatusEnum,
  };
}
