/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentInitiationDetails } from './paymentInitiationDetails';

export interface DomesticPaymentView {
  paymentId?: number;
  paymentInitiationDetails?: PaymentInitiationDetails;
  status?: DomesticPaymentView.StatusEnum;
  failureReason?: string;
}
export namespace DomesticPaymentView {
  export type StatusEnum = 'CREATED' | 'SETTLEMENT_IN_PROGRESS' | 'SETTLEMENT_IN_PROGRESS_SOURCE_ACCOUNT_DEBITED' | 'COMPLETE' | 'FAILED';
  export const StatusEnum = {
    CREATED: 'CREATED' as StatusEnum,
    SETTLEMENTINPROGRESS: 'SETTLEMENT_IN_PROGRESS' as StatusEnum,
    SETTLEMENTINPROGRESSSOURCEACCOUNTDEBITED: 'SETTLEMENT_IN_PROGRESS_SOURCE_ACCOUNT_DEBITED' as StatusEnum,
    COMPLETE: 'COMPLETE' as StatusEnum,
    FAILED: 'FAILED' as StatusEnum,
  };
}
