/**
 * Barclays 2022 CBDC Hackathon API
 * API for the Barclays 2022 CBDC Hackathon.  Please ensure you include your API key in the `x-api-key` header for your requests.
 *
 * OpenAPI spec version: 0.0.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OwnedAccount } from './ownedAccount';

export interface PartyView {
  id?: number;
  status?: PartyView.StatusEnum;
  type?: PartyView.TypeEnum;
  fullLegalName?: string;
  postalAddress?: string;
  accountsOwned?: Array<OwnedAccount>;
}
export namespace PartyView {
  export type StatusEnum = 'ACTIVE' | 'INACTIVE';
  export const StatusEnum = {
    ACTIVE: 'ACTIVE' as StatusEnum,
    INACTIVE: 'INACTIVE' as StatusEnum,
  };
  export type TypeEnum = 'INDIVIDUAL' | 'PUBLIC_LIMITED_COMPANY' | 'PRIVATE_LIMITED_COMPANY';
  export const TypeEnum = {
    INDIVIDUAL: 'INDIVIDUAL' as TypeEnum,
    PUBLICLIMITEDCOMPANY: 'PUBLIC_LIMITED_COMPANY' as TypeEnum,
    PRIVATELIMITEDCOMPANY: 'PRIVATE_LIMITED_COMPANY' as TypeEnum,
  };
}
